include-file = ~/.config/polybar/colors.ini

[colors]
background = #2e3440
background-alt = #88c0d0
foreground = #eceff4
primary = #88c0d0
secondary = #81a1c1
alert = #b48ead
disabled = #3b4252

[bar/main]
font-0 = "Inconsolata LGC Nerd Font Mono:size=11;2"
font-1 = "Inconsolata LGC Nerd Font Mono:size=11:weight=bold;2"
font-2 = "FontAwesome:size=11;2"
font-3 = "FontAwesome:size=11;2"
font-4 = RobotoMono Nerd Font:size=12;4
font-5 = Iosevka Nerd Font:size=12;2
font-6 = icomoon\-feather:size=14;2
offset-y = 5
offset-x = 5
width = 99.2679%
height = 30
fixed-center = true
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3
radius = 0
padding-right = 2pt
module-margin = 8pt
separator = |
separator-foreground = ${colors.disabled}
modules-left = i3 pulseaudio xkeyboard pacmanupdates
modules-center = datetime 
modules-right = playerctl weather eth systray powermenu
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
override-redirect = false
wm-restack = i3

[module/systray]
type = internal/tray
format-margin = 0
tray-spacing = 8

[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${color.snow2}
label-active-padding = 1
label-occupied = %name%
label-occupied-padding = 1
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
label-mounted = %{T5}󱛟%{T-} %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}
click-right = thunar

[module/weather]
type = custom/script
exec = ~/.config/polybar/scripts/weather-plugin.sh
tail = false
interval = 1000
click-left = firefox -new-tab 'https://openweathermap.org/city/4367175'

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix-foreground = ${color.snow2}
format-volume = %{T5}<ramp-volume>%{T-} <label-volume>
label-volume = %percentage%%
interval = 4
ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰕾
ramp-volume-foreground = ${color.snow2}
label-muted = muted
label-muted-foreground = ${color.red}
click-right = pavucontrol

[module/xkeyboard]
type = internal/xkeyboard
format = <label-layout>
format-spacing = 2pt
label-layout = %name% 
label-indicator-on = %name%
label-layout-foreground = ${color.snow2}
label-indicator-on-numlock = 
label-indicator-on-scrolllock = 
label-indicator-padding = 2
label-indicator-margin = 2
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/pacmanupdates]
type = custom/script
exec = checkupdates | wc -l
interval = 1000
label = %output%
format-foreground = ${color.snow2}
format-background = ${colors.background}
format-prefix = "%{T5}  %{T-}"
click-left = exec ghostty -e cachy-update

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-font = 5
format-prefix-foreground = ${color.snow2}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-font = 5
format-prefix-foreground = ${color.snow2}
label = %percentage:2%% 

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#88c0d0}%ifname%%{F#b6d8e2} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#88c0d0}%ifname%%{F-} %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
interface = eno1
unknown-as-up = true
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-color = ${color.snow2}
label-connected = %{T5}󰢾%{T-} ZTI1
label-connected-foreground = ${color.snow2}
label-disconnected = 󰞃 disconnected
label-disconnected-foreground = ${color.red}
speed-unit = ''

[module/date]
type = internal/date
interval = 1
date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S
label = %date%
label-foreground = ${color.snow2}

; custom modules
[module/i3]
type = internal/i3
pin-workspaces = false
strip-wsnumbers = true
index-sort = true
enable-click = true
enable-scroll = false
wrapping-scroll = false
reverse-scroll = false
fuzzy-match = true
format = <label-state> <label-mode>
label-mode = %mode%
label-mode-padding = 2
label-mode-background = ${color.red}
label-mode-foreground = ${color.red}
label-focused = %index%
label-focused-foreground = ${color.snow2}
label-focused-background = ${color.polar1}
label-focused-underline = ${color.orange}
label-focused-padding = 2
label-unfocused = %index%
label-unfocused-padding = 2
label-visible = %index%
label-visible-underline = #555555
label-visible-padding = 2
label-urgent = %index%
label-urgent-foreground = #000000
label-urgent-background = #bd2c40
label-urgent-padding = 2
label-separator =
label-separator-padding = 0
label-separator-foreground = #ffb52a

[module/powermenu]
type = custom/menu
format-foreground = ${colors.foreground}
format-background = ${colors.background}
label-open = "%{T5}⏻%{T-} "
label-close = "%{T5}%{T-} "
label-close-foreground = ${colors.foreground}
label-separator = " "
label-separator-foreground = ${colors.foreground}
menu-0-1 = %{T5} %{T-}
menu-0-1-exec = systemctl reboot
menu-0-1-foreground = ${colors.foreground}
menu-0-0 = "%{T5}%{T-} "
menu-0-0-exec = systemctl poweroff
menu-0-0-foreground = ${colors.foreground}

[module/datetime]
type = internal/date
interval = 1.0
date = %A, %B %d
time = %I:%M
date-alt = %A, %d %B %Y
time-alt = %k:%M:%S
format = <label>
label = "%date%  %time%"
label-padding-left = 2
label-padding-right = 2
label-alignment = center
format-prefix-foreground = ${colors.foreground}
format-prefix-background = ${colors.background}
format-prefix-underline  = ${colors.foreground}
format-prefix-overline  = ${colors.foreground}
format-prefix-padding = 0
label-background = ${color.frost1}
label-foreground = ${colors.background}
click-left = calcurse

[module/title]
type = internal/xwindow

[module/temperature]
type = internal/temperature
warn-temperature = 80
format = <label>
format-warn = <label-warn>
label = %{F#88c0d0} %{F-}%temperature-c%
label-warn =  %temperature-c%
label-warn-foreground = #bf616a

[module/cava]
type = custom/script
tail = true
exec = ~/.config/polybar/scripts/cava.sh
format = <label>
format-font = 5
format-margin = 1
format-padding = 1
label-foreground = ${color.purple}
label = %output%

[module/playerctl]
type = custom/script
interval = 2
format-font = 5
exec = echo $(playerctl metadata -f '%{T1}{{artist}} - {{title}}%{T-}' 2>/dev/null | sed -E 's/(.{50}).+/\1.../') %{A1:playerctl previous:}%{T5}%{T-}%{A} %{A1:playerctl play-pause:}$(playerctl status 2>/dev/null | grep Playing >/dev/null && echo '%{T5}  %{T-}' || echo '%{T5}  %{T-}')%{A} %{A1:playerctl next:}%{T5}%{T-} %{A}
exec-if = playerctl metadata -f {{playerName}} 2>/dev/null | grep -Ev 'mopidy' >/dev/null

[settings]
screenchange-reload = true
compositing-background = source
compositing-overline = over
compositing-underline = over
compositing-foreground = over
compositing-border = over
pseudo-transparency = false

[global/wm]
margin-top = 5
margin-bottom = 5

; vim:ft=dosini
